### ISSUE TITLE
demo中的on_key_event

### ISSUE THREAD

**Issue by Harinlen** [KevinEmiya/EmbeddedBrowserDemo#1]
咱大概看了眼demo，其实不是很推荐直接劫持键盘事件然后以事件的形式发出来。
按照代码的实现看来，真正需要的应该是QAction，然后定义响应范围是整个Application。毕竟一个Widget内部的键盘事件转发出去由另一个人处理这个有点……感觉哪里不对。
希望作者sama考虑一下（笑

**Comment by KevinEmiya** [comment]
h酱说的是cef的那个吗，那个是小时候写的代码直接搬过来的，后面还会调整的哟～😙

**Comment by Harinlen** [comment]
是的说=w=
哦~！！

**Comment by KevinEmiya** [comment]
fixed in commit: d1a0fd4
